# Generated by Django 3.0.5 on 2020-05-25 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_apk', '0002_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
